### PR TITLE
Undeprecate execCommand("useCSS")

### PR DESCRIPTION
**Pull request by saschanaz**
Since useCSS is supported everywhere and we have no plan to remove it, user agents should not emit a deprecation warning.

The following tasks have been completed:

 * [x] Confirmed there are no *new* ReSpec errors or warnings.
 * [ ] Modified Web platform tests (link to pull request)

Implementation commitment:

 * [x] WebKit (https://bugs.webkit.org/show_bug.cgi?id=36683)
 * [ ] Chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=)
 * [ ] Gecko (https://bugzilla.mozilla.org/show_bug.cgi?id=)

### CODE REVIEW

**Comment by johanneswilm** [comment]
@saschanaz Should we put this on the agenda for the call next week so that we can get a decision on whether or not to move ahead with this?

**Comment by saschanaz** [comment]
Sounds good to me, @masayuki-nakano does this patch sound good to you?

**Comment by johanneswilm** [comment]
@saschanaz Are you saying that we should readd `useCSS` because there is an advantage of using it over `styleWithCSS`? Or do you want it to say that `styleWithCSS` is still the preferred way and `useCSS` should just be listed as non-deprecated because it actually is still working in all current browsers (as a reverse alias for `styleWithCSS`)?

**Comment by saschanaz** [comment]
The latter. I just want to remove the deprecation notice because AFAIK that's generally for features that will disappear anytime soon, which is not the case here. (Unless anyone wants to remove it)

**Comment by johanneswilm** [comment]
I would personally be in favor of adding a small note pointing out that it is doing the same as `styleWithCSS` but with reverse values, and otherwise to "undeprecate" it the way you have done here - unless it is doing something else in some situations.

**Comment by travisleithead** [comment]
WG Call: Ask @saschanaz to files bugs on implementations that may be firing deprecation warnings, and then we'll merge the PR.

**Comment by saschanaz** [comment]
> 
> 
> WG Call: Ask @saschanaz to files bugs on implementations that may be firing deprecation warnings, and then we'll merge the PR.

Confirmed that Firefox, Chrome, and WebKit (on Windows build) all fire no warning for `document.execCommand("useCSS", false, false)`.

**Review by johanneswilm — APPROVED** [review]

**Pull request merged**
