### PR TITLE
Update EditContext explainer and associated examples

### PR DESCRIPTION
**Pull request by ksl871**
This PR adds a new section "Difference between DIV with Contenteditable and DIV with EditContext" to the explainer and updates examples/WebIDL sections to reflect the latest status of the EditContext development.

### CODE REVIEW

**Comment by ksl871** [comment]
+@gked

**Comment by ksl871** [comment]
+@BoCupp-Microsoft
+@snianu

**Comment by ksl871** [comment]
-@gked
-@snianu
-@BoCupp-Microsoft

**Comment by alexkeng** [comment]
close the PR since it was opened with a wrong account. sorry for inconvenience.

**Pull request closed without merging**
