### PR TITLE
Update meeting invite link

### PR DESCRIPTION
**Pull request by johanneswilm**

### CODE REVIEW

**Comment by travisleithead** [comment]
Something's still not working with this link. Is it supposed to add the calendar appointment to my Google calendar? When I click on it, it appears to be trying to look up the meeting on my google calendar (when I'm logged in) and of course, I don't have it, so it can't find it. I thought the link should be trying to add the invite to my own calendar, not looking for an existing meeting...

**Comment by travisleithead** [comment]
Do we want to just provide an ICS file?

**Comment by johanneswilm** [comment]
@travisleithead I think an ICS file would be a better chocie as it doesn't depend on any specific platform.

**Comment by travisleithead** [comment]
Is it possible to copy an ICS file into our repo and just link to it from the readme page? Do you have another idea on how to provide an ICS file?

**Comment by BoCupp-Microsoft** [comment]
> Is it possible to copy an ICS file into our repo and just link to it from the readme page? Do you have another idea on how to provide an ICS file?

Seems doable.  GitHub wouldn't let me attach an ICS to this comment, but if you paste the 38 lines below into a file with an ICS extension, I think you could add it to your PR along with a link to download it:

BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VTIMEZONE
TZID:America/Los_Angeles
LAST-MODIFIED:20201011T015911Z
TZURL:http://tzurl.org/zoneinfo-outlook/America/Los_Angeles
X-LIC-LOCATION:America/Los_Angeles
BEGIN:DAYLIGHT
TZNAME:PDT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
DTSTART:19700308T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT
BEGIN:STANDARD
TZNAME:PST
TZOFFSETFROM:-0700
TZOFFSETTO:-0800
DTSTART:19701101T020000
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTAMP:20220411T032923Z
UID:1649647725442-83447@ical.marudot.com
DTSTART;TZID=America/Los_Angeles:20220414T080000
RRULE:FREQ=MONTHLY;BYDAY=2TH
DTEND;TZID=America/Los_Angeles:20220414T090000
SUMMARY:W3C Editing WG Meeting
DESCRIPTION:Meetings are held on the second Thursday of each month at 8:00AM Pacific Time.\n\nMeetings are conducted with the help of jitsi.org video conferencing technology and the W3C's editing IRC channel. \n\nhttps://meet.jit.si/W3CEditingCall\n\nIRC Server: irc.w3.org\nChannel: #editing
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:W3C Editing WG Meeting
TRIGGER:-PT15M
END:VALARM
END:VEVENT
END:VCALENDAR

**Review by travisleithead — DISMISSED** [review]
I like Bo's suggestion.

**Review by BoCupp-Microsoft — APPROVED** [review]

**Review by johanneswilm — COMMENTED** [review]
I think this is now out of date.

**Pull request merged**
