### PR TITLE
[execCommand] use inline element syntax

### PR DESCRIPTION
**Pull request by saschanaz**
Batch-converted with `<code[\s\n]*class=[\s\n]*"external"[\s\n]*data-anolis-spec=[\s\n]*"html"[\s\n]*title=[\s\n]*"(?:the )?\w+(?: element)?"><a[\s\n]*href=[\s\n]*[^>]+>[\s\n]*(\w+)[\s\n]*</a>[\s\n]*</code>`.

### CODE REVIEW

**Comment by saschanaz** [comment]
@sidvishnoi, any idea why `[^sub^]` and `[^sup^]` don't work? Strangely https://respec.org/xref shows nothing for them.

**Comment by sidvishnoi** [comment]
They are not in our data base because HTML spec didn't export them.

**Comment by saschanaz** [comment]
Should an issue be filed on HTML? I don't see why the difference happens because I don't see any explicit export on [`<strong>`](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-strong-element).

**Comment by marcoscaceres** [comment]
Yeah, we should make sure they get exported from HTML. Could you please file a bug?

**Comment by saschanaz** [comment]
Filed https://github.com/whatwg/html/issues/4863. I don't think it's a blocker though, this already is a big change.

**Review by marcoscaceres — APPROVED** [review]
Agree. This is just non-normative ReSpec refactor.

**Pull request merged**
