### PR TITLE
Restructuring the repo for easier navigation

### LINKED ISSUE #232: Restructure the repo a bit for easy navigation

### PR DESCRIPTION
**Pull request by gked**
Closes #232 

The following tasks have been completed:

 * [ ] Confirmed there are no ReSpec/BikeShed errors or warnings.
 * [ ] Modified Web platform tests (link to pull request)

Implementation commitment:

 * [ ] WebKit (https://bugs.webkit.org/show_bug.cgi?id=)
 * [ ] Chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=)
 * [ ] Gecko (https://bugzilla.mozilla.org/show_bug.cgi?id=)

### CODE REVIEW

**Review by johanneswilm — APPROVED** [review]
In general this looks good to me. Note that several of these files really only contain a link to another file. These link files were created whenever a document changed name, so that links linking to that file would not end up being dead. This is a practice I took over from those who maintained this repository before me.

If W3C rules and common practices do not require us to keep old links intact, then we might just as well delete all those files that just contain links. For example, contentEditableTyping/Events/Intentions/etc. were all the same document that just changed its name over time as our focus shifted.

**Comment by gked** [comment]
> In general this looks good to me. Note that several of these files really only contain a link to another file. These link files were created whenever a document changed name, so that links linking to that file would not end up being dead. This is a practice I took over from those who maintained this repository before me.
> 
> If W3C rules and common practices do not require us to keep old links intact, then we might just as well delete all those files that just contain links. For example, contentEditableTyping/Events/Intentions/etc. were all the same document that just changed its name over time as our focus shifted.

sounds good. We can check with Web Apps WG Chairs whether we should delete them or not.

**Comment by annevk** [comment]
This broke a bunch of links, please revert this.

**Comment by johanneswilm** [comment]
@annevk Is it ok if I readd all those link files so that clicking on any old link will automatically transport you to the new location of the file?

**Pull request merged**
