### PR TITLE
Correct links to UndoManager proposal

### PR DESCRIPTION
**Pull request by saschanaz**
Not sure there has been any significant progress, though?

### CODE REVIEW

**Comment by johanneswilm** [comment]
Is @whsieh 's repository going to be the official repo for this?

**Comment by whsieh** [comment]
I still plan on moving this to the web apps working group.

**Comment by saschanaz** [comment]
In that case I'll wait until that happen.

**Comment by johanneswilm** [comment]
@whsieh Any update on this? Will the UndoManager still be moved?

**Comment by johanneswilm** [comment]
@whsieh @saschanaz I will put this question on the agenda for the next call. If we can get the question of where the UndoManager will live resolved before then, we can remove it from the agenda again.

**Comment by travisleithead** [comment]
WG call: ACTION: @whsieh  to move undomanager to webkit/explainers, then update the issue so we can get a better link.

**Comment by whsieh** [comment]
> WG call: ACTION: @whsieh to move undomanager to webkit/explainers, then update the issue so we can get a better link.

The explainer has now been merged into the WebKit explainers repo! (link: https://github.com/WebKit/explainers/tree/main/UndoManager).

**Review by travisleithead — APPROVED** [review]

**Comment by travisleithead** [comment]
Fantastic. Thanks everyone.

**Pull request merged**
