### PR TITLE
Change the types used on macOS

### LINKED ISSUE #412: The Web Custom formats specification does not appropriately use the macOS API
I encountered the code implementing https://github.com/w3c/editing/blob/gh-pages/docs/clipboard-pickling/explainer.md#detailed-design-discussion inside of Chromium and was pointed here. This specification does not use the macOS clipboard API appropriately and this should be fixed before shipping.

The first issue is naming. The custom format map is specified to have the format type `com.web.custom.format.map`, and the various formats are specified to have the format names `com.web.custom.format[\d+]`. This specification is not the work of [web.com](http://web.com/), and thus using the `com.web.*` prefix is inappropriate. If this is a W3C specification, a prefix of `org.w3.*` is probably the most appropriate.

The second issue is the existence of a custom format map. [Edit: This aspect of the proposal turns out to not be viable; see my followup below.] On platforms for which there is a limit on the number of formats, this might make sense. But on the Mac, types are just reverse-domain strings, and so keeping a map strikes me as a waste. Would there be an issue in not having a map type on the Mac, and instead just doing a mapping of, say, the `text/html` type to `org.w3.web-custom-format.text-html`, `my/wackytype` to `org.w3.web-custom-format.my-wackytype`, etc? There’s no reason that the native interface must look identical on all platforms, and since we already have to accomodate for their differences, we should take the opportunity to play to their strengths.

### PR DESCRIPTION
**Pull request by avidrissman**
This specification is not the work of web.com, and thus using the com.web.* prefix is inappropriate. Change the clipboard types used to begin with `org.w3` as this specification is theirs.

Also add macOS specific clarification.

Closes #412 

The following tasks have been completed:

 * [ ] Confirmed there are no ReSpec/BikeShed errors or warnings.
 * [ ] Modified Web platform tests (link to pull request)

Implementation commitment:

 * [ ] WebKit (https://bugs.webkit.org/show_bug.cgi?id=)
   * I don’t believe this spec is currently implemented in WebKit, and therefore the implementation commitment for this PR is subsumed by the implementation commitment for this spec and is inapplicable
 * [X] Chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=1401040)
   * A CL, https://chromium-review.googlesource.com/c/chromium/src/+/4108170, is complete
 * [ ] Gecko (https://bugzilla.mozilla.org/show_bug.cgi?id=)
   * I don’t believe this spec is currently implemented in Gecko, and therefore the implementation commitment for this PR is subsumed by the implementation commitment for this spec and is inapplicable

### CODE REVIEW

**Comment by snianu** [comment]
The changes look good to me, but before we merge this change, we want to discuss with the EditingWG members to see if they have any feedback.

**Comment by avidrissman** [comment]
Certainly! Please reach out if the EditingWG folks have any questions.

**Comment by snianu** [comment]
We discussed this issue and no concerns were raised by the EditingWG members. Thank you @avidrissman for working on this!

**Review by snianu — APPROVED** [review]

**Comment by avidrissman** [comment]
Thank you, @snianu, for helping shepherd this along. https://crrev.com/c/4108170 is in the commit queue and should be landed soon.

Good luck in the larger task of getting this explainer merged upstream.

**Pull request merged**
