### PR TITLE
Updated the intro material to better reflect the current status.

### PR DESCRIPTION
**Pull request by njdjacobs**
Closes #????

The following tasks have been completed:

 * [ ] Confirmed there are no ReSpec/BikeShed errors or warnings.
 * [ ] Modified Web platform tests (link to pull request)

Implementation commitment:

 * [ ] WebKit (https://bugs.webkit.org/show_bug.cgi?id=)
 * [ ] Chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=)
 * [ ] Gecko (https://bugzilla.mozilla.org/show_bug.cgi?id=)

### CODE REVIEW

**Comment by johanneswilm** [comment]
This PR touches on a lot of the text that was discussed quite a lot in the past, so it should not be merged without discussing it in an Editing Taskforce meeting IMO.

**Comment by johanneswilm** [comment]
Closing this as discussion it further was not requested. Please reopen if you want us to put it on the agenda for a meeting.

**Comment by njdjacobs** [comment]
It should be reopened, but I don't seem to have permissions to do that. If I understand correctly there should be a "Reopen pull request" button beneath this comment box, but there isn't one.
reopen

**Comment by johanneswilm** [comment]
@njdjacobs Ok, so you want to bring this up at a Web Editing WG meeting then? Have you obtained Invited Expert status yet? If not, I can put you in touch with those who can help you with that.

**Comment by njdjacobs** [comment]
No, of course not. I am not an "Expert". I simply think it's unreasonable to dismiss a pull request which does nothing substantive, merely correcting some obviously outdated parts of a woefully outdated document.

If every attempt to make the document slightly less badly outdated is to be rejected, there is little point in the document's existence.

**Comment by johanneswilm** [comment]
@njdjacobs Well, you wrote to me in an email on April 10 that you did not want to go further with your proposal. I responded on April 14 that you didn't need to give up and what the initial steps of the process would look like if you wanted to continue. After that you didn't respond.

The paragraph you want to change has been heavily discussed in the past. Changing it is therefore not uncontroversial and would at least require for the change to be discussed within the working group. There is a way for you to go forward with your proposal, but I cannot just merge this without checking whether there is consensus around your proposal.

I would therefore like to encourage you to apply for Invited Expert status and present your proposal at a call, alternatively, you could discuss it with someone else who is familiar with your usecase who will go through these steps instead of you.

**Comment by njdjacobs** [comment]
On Sat, 2021-07-24 at 04:05 -0700, Johannes Wilm wrote:
> @njdjacobs Well, you wrote to me in an email on April 10 that you did
> not want to go further with your proposal. I responded on April 14
> that you didn't need to give up and what the initial steps of the
> process would look like if you wanted to continue. After that you
> didn't respond.
> The paragraph you want to change has been heavily discussed in the
> past. Changing it is therefore not uncontroversial and would at least
> require for the change to be discussed within the working group.
> There is a way for you to go forward with your proposal, but I cannot
> just merge this without checking whether there is consensus around
> your proposal.
> I would therefore like to encourage you to apply for Invited Expert
> status and present your proposal at a call, alternatively, you could
> discuss it with someone else who is familiar with your usecase who
> will go through these steps instead of you.
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
My suggested changes make no recommendations of any kind. They merely
replace statements (about the current implementations) which were
correct at the time they were written, but which are now false because
the implementations have long ago changed. If replacing false
statements by true statements is "not uncontroversial", then the
working group has problems which are beyond the capability of an
outsider like myself to fix.

You could leave the pull request open. Maybe the situation will change.
One alternative, in my opinion, would be to scrap the whole document,
perhaps replacing it with a one-sentence placeholder simply stating
that browsers have implemented execCommand but that it is deprecated
and will not be the subject of a standards-track document. That would
surely be less misleading than an outdated document.

**Comment by saschanaz** [comment]
Maybe at least explain why you think they are outdated sentence-by-sentence?

**Comment by johanneswilm** [comment]
The initial discussion about this was mainly on the email list. Try reading the email thread with the title "existing contenteditable spec" [1] That then turned into a meeting. A few months later, the wording again came up for discussion under the thread "on execCommand() and script-triggered copy/cut/paste" [2]. The parts that were discussed at informal parts of the F2F meetings were not captured there. If I recall correctly, it was mainly a question of whether the feature should be marked as "deprecated" or  whether it should be classified as "we may work on this again some time in the future". Especially the Chromium team was very clear about their view: they would not change their implementation due to anything any spec would ever say, but they might under some circumstances change their implementation of individual features to be closer to that of other browsers. The final wording there was carefully negotiated and was not easily reached at as there were several different positions to cover.

It is true that positions may change and that may just have happened here. But given that it has been a major decision to go away from trying to get execCommand to work for editors and instead to work on other mechanisms, and that this wording was negotiated, I think such a change would at the least be needed to be discussed on the mailing list and all the involved parties should be consulted.

So yes - let's put this on the agenda for a call or let's have a new discussion on the email list about this. And I would think that @njdjacobs should probably sign some type of agreement with the W3C, as such a discussion would possibly also involve things that are relevant in terms of intellectual property, licenses, etc. .

[1] https://lists.w3.org/Archives/Public/public-editing-tf/2015May/thread.html

[2] https://lists.w3.org/Archives/Public/public-editing-tf/2015Aug/thread.html

**Comment by njdjacobs** [comment]
Having browsed the August 2015 messages, I have even less understanding
of the objections to the very minimal changes in my pull request.

The Chrome team seems to have been doing what they apparently said they
were doing, i.e. converging to some extent with the Mozilla
implementation.

If I were ever to do any significant amount of work on the execCommand
spec, my goal would be to end up with essentially a descriptive, not a
normative, document. In other words, I would try to produce a document
that described a common subset of execCommand functionality that the
major browsers (Chrome, Android, Firefox, Safari) already implement,
omitting behaviour that conflicts with other standards. I'm coming at
it from a "user" standpoint (my background is website development, not
browser development) and of course a website developer needs a document
that tells what is going to work in all (recent) browsers. As people on
that thread already pointed out, no browser is going to throw away
execCommand in the foreseeable future, and any new browser would have
to implement it.
So a specification is needed, and the present state of the spec is far
from adequate.

I understand that this isn't how the standards community normally
works. Maybe that means that I'm not the right person to do this. But
the present state of the spec helps nobody and guides nobody. Saying
that execCommand is obsolete, and that all the websites currently using
it will have to migrate to a forthcoming replacement, is egregiously
unrealistic.

Discussion, and consensus with browser developers, would be needed
before putting anything in the spec beyond what all major browsers do
already. But I'm not proposing any such extension, so where is the
controversy?

**Comment by johanneswilm** [comment]
@njdjacobs As I stated before - it's entirely possible that a consensus can be formed around a different wording for that paragraph. It's just not clear that is the case. The current wording basically tells JS devs to stay away from execCommand if they expect it to work well across browsers. Your wording would take that notice away. If major new projects were to try to start creating a new execCommand based editor due to the changed notice and it turned out it doesn't work as well across browsers as you are saying, then that might put pressure on browser makers to shift their resources toward execCommand and thereby take away resources from other areas. The current wording was negotiated in a complex setting and so this is not a decision you and I can just take to change that notice now.

I really suggest for you to please either present your proposal at a call or as an email on the email list so that we really can have a real discussion on it. And if I understand you correctly, you have tested all aspects on all browsers and have checked that execCommand now work the exact same way on all browsers. If you have done that, then there should be no problem calling yourself an "expert" on the matter either.

**Comment by njdjacobs** [comment]
I did not write that. I have tested a useful subset of the
functionality on current versions of the major browsers.
As for "all browsers", I don't even know how many browsers exist today.
I named only four.

**Comment by johanneswilm** [comment]
Ok, but so that is a useful starting point then. If you could document that useful subset, then that would seem like a good starting point for discussing this again. Maybe we could have a document that only covers such a useful subset. There are only three main rendering engines out there right now and mostly those will likely correspond with differences in execCommand behavior.

**Comment by njdjacobs** [comment]
I'm not going to do anything further until the pull request I have
already submitted is resolved.
Adding to the queue of material that you regard as "controversial" does
not seem useful.

Does anyone else who has read it think it is controversial?

**Comment by johanneswilm** [comment]
Ok, well if you don't want to engage with the working group, you don't want to provide evidence for your claim of changed circumstances, and you don't want to sign the agreements outsiders normally sign with the W3C, then I don't see a way forward for your proposal.

Feel free to come back at a later stage with this or a similar proposal if you then are willing to do one of the things I suggested above. This PR will not be reopened until such time.

**Comment by njdjacobs** [comment]
As I have already indicated to you, I am perfectly willing to sign an
agreement renouncing any "intellectual property" rights etc. I asked
you what the procedure was for this and you did not reply.

**Comment by njdjacobs** [comment]
I thought that submitting a pull request was "engaging with the working
group"?
It is there for people to read. Engagement is a 2-way street. I've
started, engagement can only continue with a response.

**Comment by johanneswilm** [comment]
> As I have already indicated to you, I am perfectly willing to sign an agreement renouncing any "intellectual property" rights etc. I asked you what the procedure was for this and you did not reply.

I cannot see that I have received an email from you making such a request. I can put you in contact with the people who can help you with obtaining Invited Expert status - if that is what you want.

> I thought that submitting a pull request was "engaging with the working group"? It is there for people to read. Engagement is a 2-way street. I've started, engagement can only continue with a response.

As I have now explained to you multiple times, the change you are proposing is touching an area that has been very controversially discussed in the past and therefore I cannot just change because a random anonymous person on the internet claims that the circumstances have changed. This would be very different if the change was concerned with some other note in another spec where there has been no prior controversy.

You say that you have tested a "meaningful subset" in 4 major browsers and they all work the same. Then I'd suggest you sign up with IE status, and you create a test suite for that subset and then you make a post on the mailing list linking to your test suite and making an argument in favor of us writing a spec that describes this meaningful subset. Subsequently, because this would mark such a major shift in where we are going, we should also put it on the agenda of a meeting where we know that all major interest groups will be present.

**Comment by njdjacobs** [comment]
On Tue, 2021-07-27 at 07:02 -0700, Johannes Wilm wrote:
> > As I have already indicated to you, I am perfectly willing to sign
> > an agreement renouncing any "intellectual property" rights etc. I
> > asked you what the procedure was for this and you did not reply.
> I cannot see that I have received an email from you making such a
> request. I can put you in contact with the people who can help you
> with obtaining Invited Expert status - if that is what you want.
[snipped]

Attached is a copy of the email "making such a request", with headers
in case you need help finding it in your inbox. I sent it to you
personally, not to the list; it simply didn't occur to me that you
might later send a message to the list denying having received it.

However, if your intention is to block any progress on the document,
don't worry: I'm not going to try to do anything further about it. (Nor
have I any intention of misrepresenting myself as any kind of
"expert".)

**Comment by johanneswilm** [comment]
Hey @njdjacobs ,
currently you are commenting on a closed issue on Github. I don't think your attachment came through here. The email list that I have been referring to earlier has a different adress: public-editing-tf@w3.org . 

It's of course entirely possible that I misread an email from you or that I somehow didn't receive it. I am certainly not trying to misrepresent our email conversation here in this GitHub issue. Just let me know if you want to go through with the process as outlined above or not and I'll try to help you as much as I can if you are willing to follow the procedures.

"Invited Expert" is simply the term that is used in W3C context for someone who is more-than-average knowledgeable on a certain topic and who therefore needs to participate in certain discussions in spite of not being affiliated with a W3C member organization. If you don't have an exceptional level of knowledge about this spec, then surely you would not try to get it changed, right?

**Comment by saschanaz** [comment]
Yeah, being an invited expert does not require any degree of any form, so don't hesitate 😀

**Pull request closed without merging**
